### ISSUE TITLE
Making Use of CSS inheritance

### ISSUE THREAD

**Issue by jim-rosales** [RichardSp8/prj-rev-bwfs-dasmoto#4]
When writing CSS styles, it's best to avoid repeating styles in your stylesheet. For example here your repeat the following styles three separate times.

```CSS
  font-family: Helvetica;
  font-size: 32px;
  font-weight: bold;
  color: white;
```

Instead, it is best to make use of CSS inheritance try and reduce the amount of duplicate code. In this case, you can apply the styles all the `h2's` share to the generic`h2` element, and then apply their unique color using each `h2's` id. 

For example:
```CSS
h2 {
  font-family: Helvetica;
  font-size: 32px;
  font-weight: bold;
  color: white;
}

#brush {
  background-color: mediumspringgreen;
  
}

#frame {
  background-color: lightcoral;
}

#paint {
  background-color: skyblue;
}
```

https://github.com/Richard-Speight/prj-rev-bwfs-dasmoto/blob/90f963ddd7974b32a3dddd3a7f10515cfc2f30de/dasmotoSite/resources/style.css#L20-L42
